# This file contains values from Cookiecutter

default_context:
  project_name: "risk_poc"
  project_description: "risk evaluation version"
  organization: "aarelaponin"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "aarelaponin"
  email: "aarelaponin@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
